//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvw_ShowBlogs
    {
        public int BlogID { get; set; }
        public string BlogTitle { get; set; }
        public string BlogCategory { get; set; }
        public string BlogAuthor { get; set; }
        public string BlogBody { get; set; }
        public string BlogCreateDate { get; set; }
        public string BlogCreateTime { get; set; }
        public byte[] BlogPicture { get; set; }
    }
}
